main_source/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]


urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from users import views as user_views


app_name = 'users'


urlpatterns = [
    path('register/', user_views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.ProfileView.as_view(), name='profile'),
    path('profile-update/<int:pk>/',
         user_views.ProfileUpdate.as_view(), name='update_profile'),
    path('activate/<uidb64>/<token>/',
         user_views.activate_account, name='activate'),
    path('password-change/', user_views.UserPasswordChangeView.as_view(),
         name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        success_url=reverse_lazy('users:password_reset_done'),
        email_template_name='users/password_reset_email.html'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')
    ), name='password_reset_confirm'),

    path('password-reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.conf import settings
from django.shortcuts import reverse


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email required for Registration')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        user = self.create_user(email=email, password=password)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user


class UserModel(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    image = models.ImageField(upload_to='profiles', default='profiles/default_profile.jpg')
    about_me = models.CharField(max_length=255, blank=True, null=True) 
    location = models.CharField(max_length=25, blank=True, null=True)
    phone = models.CharField(max_length=10, blank=True, null=True)  

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

    # To make name fields required
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

users/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import get_user_model, login
from django.views.generic import View, UpdateView, DetailView, TemplateView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy

from .forms import RegisterForm
from .models import Profile
from .tokens import account_activation_token

class OwnerOnlyMixin:
    """Authorize only the owner of the object to update or delete an item"""
    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.user == request.user:
            return super().dispatch(request, *args, **kwargs)
        else:
            return HttpResponse('Unauthorized', status=401)

class RegisterView(View):
    """To register a new user with email-verification"""
    def get(self, request, *args, **kwargs):
        form = RegisterForm()
        return render(request, 'users/register.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            user.profile.first_name = first_name
            user.profile.last_name = last_name
            user.save()
            # registraion via email verification
            current_site = get_current_site(request)
            email_subject = "Please complete you registration"
            message = render_to_string('users/user_activation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
            messages.success(request, 'Activation link sent you your email ID. Please check you inbox')
            return redirect('users:login')
        # messages.error(request, 'Sorry username already taken')
        return render(request, 'users/register.html', {'form': form})

def activate_account(request, uidb64, token):
    """To activate the user profile after validating the token"""
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = get_user_model().objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, get_user_model().ObjectDoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "Your account has been activated successfully!")
        return redirect('users:profile')
    
    messages.error(request, 'Activation link is invalid!')
    return redirect('users:register')


class ProfileView(LoginRequiredMixin, TemplateView):
    """To display the User Profile"""
    # model = Profile
    template_name = 'users/profile.html'


class ProfileUpdate(LoginRequiredMixin, OwnerOnlyMixin, UpdateView):
    """To update the user profile"""
    model = Profile
    fields = ('first_name', 'last_name', 'image', 'location', 'about_me', 'phone')
    success_url = reverse_lazy('users:profile')


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users App</title>
    <!-- bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</head>

<body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-info">
        <a class="navbar-brand" href="#">SomeLogo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04"
            aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav mr-auto ">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown04" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Dropdown</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown04">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">Hello {{user.profile.first_name}}</a>
                    <div class="dropdown-menu" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'users:password_change' %}">Change Password</a>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                    </div>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="#">Another Link</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
                </li>

                {% endif %}
            </ul>

        </div>
    </nav>


    <!-- messages -->
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
    </div>


    <!-- body block -->

    {% block body %}

    {% endblock %}


</body>

</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row mt-4 mb-4">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow mt-4 bg-white rounded">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h4>Login</h4>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-info float-right">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row mt-4 mb-4">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow mt-4 bg-white rounded">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h4>Logout</h4>
                    </div>
                </div>
                <div class="card-body">
                    <p>Thanks for visiting us. See you around Soon!</p>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/password_change_done.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h5>Password Change</h5>
                    </div>
                </div>
                <div class="card-body">
                    <p>Password Changed Successfully</p>
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h5>Change Password</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="alert alert-info">
        Your Password has been reset successfully.
    </div>
    <a href="{% url 'users:login' %}">Login</a>
</div>


{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h5>Password Reset</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-primary">Reset Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="alert alert-info">
        Password reset link has been sent to your registered email. Please check your inbox.
    </div>
</div>


{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
	
{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
	
{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h5>Password Reset</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% block body %}
<div class="container">
    <div class="row">

        <div class="col-md-4 order-md-1 mb-4">

            <div class="card mt-3 shadow p-3 mb-3 bg-white rounded">
                <div class="row">
                    <div class="col-md-8 offset-md-2 mt-4 mb-4">
                        <img src="{{user.profile.image.url}}" class="rounded-circle card-img-top">
                    </div>
                </div>

                <div class="card-body">
                    <h5 class="card-title text-center">{{user.profile.first_name | capfirst}}
                        {{user.profile.last_name | capfirst }}</h5>
                    <p class="text-center">{{user.profile.location | default_if_none:"Location"}}</p>
                </div>
            </div>

        </div>

        <div class="col-md-8 order-md-2">

            <div class="card mt-3 shadow p-3 mb-3 bg-white rounded">
                <div class="row">
                    <div class="col-md-6">
                        <h4>Profile Summary</h4>
                    </div>
                    <div class="col-md-6">
                        {% if user == request.user %}
                        <a href="{% url 'users:update_profile' user.profile.id %}" class="btn btn-outline-info float-right"
                            style="color: black;">Update</a>
                        {% endif %}
                    </div>
                </div>

                <hr>
                <div>
                    <h5>About Me</h5>
                    <p>{{user.profile.about_me | default:""}}</p>
                </div>
                <div>
                    <h5>Email</h5>
                    {% if user == request.user %}
                    <p>{{user.email}}</p>
                    {% endif %}
                </div>

            </div>
            <div class="header">
                <hr>
                <h5>Posts</h5>
                <hr>
            </div>
            {% for object in user.profile.get_recipes %}
            {% include 'core/_post.html' %}
            {% endfor %}

        </div>

    </div>
</div>

{% endblock %}

users/templates/users/profile_form.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-4">
            <div class="card shadow">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        <h5>Update Profile</h5>
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <div class="row mt-4 mb-4">
        <div class="col-md-6 offset-md-3">
            <div class="card shadow mt-4 bg-white rounded">
                <div class="card-header bg-info text-white">
                    <div class="card-title">
                        SignUp
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" class="btn btn-info float-right">Sign Up</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/user_activation.html
{% autoescape off %}
Hi {{ user.first_name | capfirst }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

Regards,
Team LemonGrass
{% endautoescape %}